config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  
  root 'main#index'
# Content pages
  get 'how_it_works', to: 'main#how_it_works'
  get 'faqs', to: 'main#faqs'
  get 'prohibited_items', to: 'main#prohibited_items'
  get 'terms_of_use', to: 'main#terms_of_use'
  get 'privacy_policy', to: 'main#privacy_policy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
                      sessions: 'sessions',
                      registrations: 'registrations',
                      :confirmations => 'confirmations',
                      omniauth_callbacks: "users/omniauth_callbacks"
                     }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end


#BROSING
  get '/browse', to: 'browse#index', as: 'browse'
  get '/browse_select', to: 'browse#select', as: 'browse_select'
  get '/browse/categories', to: 'browse#category', as: 'browse_categories'

#Relationships
  resources :relationships, only: [:create, :destroy]

#Gropus
  resources :groups do
    post :block_user, on: :member
    post :unblock_user, on: :member

    resources :users, only: [:show] do
    end
  end

  get 'groups_search', to: 'groups#search', as: "groups_search"
  get 'switch_groups',                  to: 'groups#switch', as: :switch_groups
  post '/choose_group/:group_id',       to: 'groups#choose_group', as: 'choose_group'
  post '/switch_group/:group_id',       to: 'groups#switch_group', as: 'switch_group'
  post '/join_group/:group_id',         to: 'groups#join_group', as: 'join_group'
  post '/leave_group/:group_id',        to: 'groups#leave_group', as: 'leave_group'
  post '/add_to_group/:user_id',        to: 'groups#add_to_group', as: 'add_to_group'
  post '/invite_to_group',              to: 'groups#invite_to_group', as: 'invite_to_group' 
  delete '/remove_from_group/:user_id', to: 'groups#remove_from_group', as: 'remove_from_group'
  post '/appoint_group_admin/:user_id', to: 'groups#appoint_admin', as: 'appoint_group_admin'
  post '/demote_group_admin/:user_id',  to: 'groups#demote_user', as: 'demote_group_admin'
  get '/more_group_items', to: 'groups#load_more', as: 'more_group_items'

#Refferal
  post 'send_invite', to: 'referral#invite', as: :send_invite
  get 'invite', to: 'referral#index', as: :invite

#FAQ
  resources :faq_items
  get 'help', to: 'faq_items#index', as: :help

# DisputsComment
  resources :disput_comments

# Disputs
  resources :disputs
  get '/open_disput_modal', to: 'disputs#open_disput_modal', as: 'open_disput_modal'
  get '/resolve_disput_modal', to: 'disputs#resolve_disput_modal', as: 'resolve_disput_modal'

# Items
  resources :items
  get 'search', to: 'items#search', as: "search"
  post '/buy_now', to: 'items#buy_now', as: 'buy_now'
  post '/buy_free', to: 'items#buy_free', as: 'buy_free'
  post '/activate_payment/:id', to: 'items#activate_payment', as: 'activate_payment'
  post '/premium_payment/:id', to: 'items#premium_payment', as: 'premium_payment'
  post '/buy_item/:id', to: 'items#buy_item', as: 'buy_item'
  post '/item/:id/offer', to: 'items#make_an_offer', as: 'make_an_offer'
  get '/items/category/:category', to: "items#index", as: "items_category"
  post 'choose_winner/:id', to: 'items#choose_winner', as: 'choose_winner'
  post 'set_winner/:id', to: 'items#set_winner', as: 'set_winner'
  post 'finish/:id', to: 'items#finish_item', as: 'finish_item'
  post 'item/:id/publish', to: 'items#publish', as: 'publish_item'
  post 'item/save_to_draft', to: 'items#save_to_draft', as: 'save_to_draft'
  patch 'item/:id/save_to_draft', to: 'items#save_to_draft', as: 'update_to_draft'
  get '/choose_posting_type', to: "items#choose_type", as: "choose_posting_type"

# Charges
  resources :charges, only: [:new, :create]

  namespace :account do
    # Messages
    post '/messages/status/:id', to: 'messages#change_status', as: 'messages_change_status'
    get '/feedback_service', to: 'messages#feedback', as: 'feedback_service'
    resources :messages, :except => [:update] do
      collection do
        delete 'destroy_multiple', to: 'messages#destroy_multiple'
      end
    end
    resources :notifications, only: [:index, :destroy]
    get '/dashboard', to: 'dashboard#index'
    get '/profile', to: 'profile#edit'
    patch '/profile', to: 'profile#update'
    get '/items', to: 'dashboard#items'
    get '/feedbacks', to: 'dashboard#feedbacks'
    get '/bids', to: 'dashboard#bids'
  end

# Likes
  put '/likes/add_to_favorite/:id/:obj', to: 'likes#add_to_favorite', as: 'add_to_favorite'
  put '/likes/remove_from_favorite/:id/:obj', to: 'likes#remove_from_favorite', as: 'remove_from_favorite'

# Photos
  post '/images/:temp_key', to: 'images#create', as: 'images_create'
  resources :images, :only => [:index, :show, :destroy]

# Bids
  resources :bids, :only => [:create]
#Feedback
  resources :feedbacks, :only => [:new, :create]

#Users
  get 'settings', to: 'users#settings', as: 'settings'
  post 'notification_permit', to: 'users#set_notification_permit', as: 'set_notification_permit'
  get 'transactions', to: 'users#transactions', as: 'transactions'
  get 'security', to: 'users#security', as: 'security'
  post '/settings/set_currency/', to: 'users#set_currency', as: 'set_currency'
  get 'my_items', to: 'users#items', as: 'my_items'
  get 'dashboard', to: 'users#dashboard'
  get 'dashboard/feedbacks', to: 'users#feedbacks'
  get 'dashboard/bids', to: 'users#bids'
  resources :users do
    collection do
      get 'new_password'
      patch 'update_password'
    end
  end
  resources :password_resets

#Balance
  resources :withdraws, :only => [:new, :create]

# Pages
  get 'pages/:id', to: 'pages#show', as: 'pages'

  get '*path' =>  redirect('/')

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :authenticate_user!, except: [:index]
  load_and_authorize_resource param_method: :group_params
  before_filter :get_group, only: [:show, :update, :edit, :destroy, :block_user, :unblock_user]
  before_filter :get_user, only: [:block_user, :unblock_user]
  before_filter :search, only: [:index]

  def index 
    if @groups.blank? || @location.blank?
      if current_user
        country = current_user.country if current_user.country.present?
        state   = current_user.state if current_user.state.present?
        city    = current_user.city if current_user.city.present?
      else
        geo_location = get_geo_location
        country = geo_location['country']
        state   = geo_location['region']
        city    = geo_location['city']
      end

      @location = ''
      @groups = Group.actives if @groups.nil?
      @groups = @groups.where(country: country) unless country.blank?

      unless state.blank?
        @groups = @groups.where(state: state)
        @location = state.upcase
      end

      unless city.blank?
        if @groups.where(city: city).present?
          @groups = @groups.where(city: city)
          @location = ' | ' + @location unless @location.blank?
          @location = city.capitalize + @location
        end
      end

      @location = 'WorldWide' if @location.blank?
    end
  end

  def new
  end

  def create
    @group = current_user.groups.build group_params
    respond_to do |format|
      if @group.valid? && params[:check]
        @group.save
        format.json {
          render json: {
              location: group_path(@group)
          }, status: 200
        }
      else
        @group.errors.add :check, "You should agree the terms and conditions of groupnshop." if params[:check].blank?
        format.js { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @items = @group.items.active.latest_items.limit(3)
  end

  def switch
    @groups = current_user.joined_groups
  end

  def edit
  end

  def update
    respond_to do |format|
      if @group.update_attributes(group_params)
        format.json {
          render json: {
              location: group_path(@group)
          }, status: 200
        }
      else
        format.js { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  def search
    if params[:q]
      @gq = Group.includes(:items, :memberships).page(params[:page]).ransack(params[:q])
      @groups = @gq.result()
      @location = params[:q][:city_or_state_cont]
    end
  end

  def invite_to_group
    group = Group.find params[:group_id]
    user = current_user
    emails = params[:email].split(',')
    sended = ''
    invalid = ''
    emails.each do |email|
      email = email.downcase.delete(' ')
      if email.count("@") != 1
        if invalid.blank?
          invalid += email
        else
          invalid += ', ' + email
        end
      elsif email =~ /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
        if sended.blank?
          sended += email 
        else
          sended += ', ' + email
        end
      else
        if invalid.blank?
          invalid += email
        else
          invalid += ', ' + email
        end
      end
    end
    if !sended.blank?
      flash[:success] = 'Invite sent to ' + sended +'.'
      sended = sended.split(',')
      GroupMailer.invite_to_group(user, sended, group).deliver
    end
    if !invalid.blank?
      flash[:error] = '"' + invalid + '"' + ' is not valid.'
    end
    redirect_to :back
  end

  def add_to_group
    @user = User.find_by_id params[:user_id]
    @group = Group.find_by_id params[:group_id]
    if @user && @group
      group_memberships = @user.group_memberships.where(group_id: @group.id)
      if !group_memberships.blank?
        group_memberships = group_memberships.first
        if group_memberships.update status: 'joined'
          respond_to do |format|
            format.js
          end
        end
      end 
    end
  end

  def remove_from_group
    @user = User.find_by_id params[:user_id]
    @group = Group.find_by_id params[:group_id]
    if @user && @group
      group_memberships = @user.group_memberships.where(group_id: @group.id)
      if !group_memberships.blank?
        group_memberships = group_memberships.first
        if group_memberships.delete
          respond_to do |format|
            format.js
          end
        end
      end
    end
  end

  def appoint_admin
    @user = User.find_by_id params[:user_id]
    @group = Group.find_by_id params[:group_id]
    if @user && @group
      @group.provide_to_admin(@user)
    end
    flash[:notice] = @user.full_name + ' is admin now.'
    redirect_to :back
  end

  def demote_user
    @user = User.find_by_id params[:user_id]
    @group = Group.find_by_id params[:group_id]
    if @user && @group
      @group.demote_to_user(@user)
    end
    flash[:notice] = @user.full_name + ' is no longer admin.'
    redirect_to :back
  end

  def leave_group
    @group = Group.find_by_id params[:group_id]
    if @group
      group_memberships = @group.group_memberships.where(user_id: current_user.id)
      if !group_memberships.blank?
        group_memberships = group_memberships.first
        group_memberships.delete
        respond_to do |format|
          format.js
        end
      end
    end
  end

  def join_group
    @group = Group.find_by_id params[:group_id]
    if @group
      current_user.group_memberships.create group_id: @group.id
      respond_to do |format|
        format.js{ flash[:notice] = "An email will be sent to you when your request to join #{ActionController::Base.helpers.link_to @group.title, group_url(@group) } is approved." }
      end
    end
  end

  def choose_group
    @group = Group.find_by_id params[:group_id]
    if @group
      rel = current_user.group_memberships.find_by(group_id: @group.id)
      rel.active!
    end
    redirect_to group_path(@group)
  end

  def switch_group
    @group = Group.find_by_id params[:group_id]
    if @group
      rel = current_user.group_memberships.find_by(group_id: @group.id)
      rel.not_active!
      rel.save
    end
    redirect_to group_path(@group)
  end

  def load_more
    @group = Group.find params[:group_id]
    @items = @group.items.active
    last_id = params[:item_id].to_i
    if last_id
      @items = @items.where('items.id < ?', last_id).latest_items.limit(3)
      items_html = ''
      counter = 0
      @items.each do |item|
        # counter+=1
        # delay = counter.to_f/20
        items_html += render_to_string :layout => false, :template => 'partials/_new_bid', :locals => {:item => item}
      end
      next_items = @group.items.active.where(id: last_id - 4).present?
    end
    # binding.pry
    respond_to do |format|
      format.json {render json: { html: items_html, next_items: next_items, status: "success"}}
    end
  end

  def block_user
    if @group.block_user(@user, current_user)
      BlockReason.create(user: @user, group: @group, reason: params[:reason])
    else
      flash[:error] = "You can't block this user!"
    end
    redirect_to group_user_path(@group, @user)
  end

  def unblock_user
    if !@group.unblock_user(@user, current_user)
      flash[:error] = "You can't unblock this user!"
    end
    redirect_to group_user_path(@group, @user)
  end


  private
  def group_params
    params.require(:group).permit(:title, :description, :rules, :terms, :file, :banner)
  end

  def get_group
    @group = Group.find(params[:id])
  end

  def get_user
    @user = User.find_by(id: params[:user_id])
    redirect_to group_path(@group) if @user.nil?
  end

end

app/views/groups/_group.slim
- if !group.state.blank?
  - country_or_state = ' | ' +  group.state.upcase + ' '
-elsif !group.country.blank?
  - country_or_state = ' | ' + group.country.upcase + ' '
-else
  - country_or_state = ' | '
-if current_user
  - member_status = current_user.group_status(group)
-else
  - member_status = ""
.bz-group
  .col-md-7.col-xs-6
    = link_to group_path(group)
      h4 class="bold"
        = 'View ' + group.title
    h4.bz-subtitle
      - if !group.city.blank? && !country_or_state.blank?
        = group.city.capitalize + country_or_state
      -if group.memberships.count == 1
        | #{group.memberships.count} member
      - else
        | #{group.memberships.count} members 
      / | 4km away
  .col-md-5.col-xs-6
    .bz-group-controls
      -if current_user
        -if member_status == "pending"
          =render "groups/invite_buttons/pending_group_btn", locals: {group: group}
        -if member_status == "joined"
          =render "groups/invite_buttons/leave_group_btn", locals: {group: group}
        -if member_status == ""
          =render "groups/invite_buttons/join_group_btn", locals: {group: group}
      -else
        = link_to '+Join to Buy or Sell', root_path(anchor: 'sign_section'), class: " bz-text-btn join_group"

app/views/groups/_group_form.slim
= semantic_form_for locals[:group], remote: true, :html => {:id => 'SUBMISSION_FORM', :class => 'validate-form', role: :form, 'data-model' => 'group', :'data-type' => 'json'} do |f|
  .form-group.field_wrapper
    = label_tag 'title', 'Name Your Group', class: "light"
    = f.input 'title', label: false, class: 'form-control', placeholder: '', input_html: {class: "form-control"}
  .form-group.field_wrapper
    = label_tag 'description', 'Describe Your Group', class: "light"
    = f.text_area 'description', label: false , class: 'form-control', rows: 4, placeholder: '', input_html: {class: "form-control"}
  .form-group.field_wrapper
    = label_tag 'file', 'Select group images', class: "light"
    .image-fields-group
      .col-xs-6.p-0 
        .image-field.custom_image_field
          = label_tag 'file', 'Select a banner for your Group', class: "light image_field_text" 
          = f.input :banner, type: :file, label: false, input_html: {class: 'image_field_input'}
      .col-xs-6.p-0
        .image-field.custom_image_field
          = label_tag 'file', 'Select a Group Admin image', class: "light image_field_text"
          = f.input :file, type: :file, label: false, input_html: {class: 'image_field_input'}
  / = label_tag 'rules', 'Rules and regulations of group', class: "light"
  / = f.text_area 'rules', label: false , class: 'form-control', rows: 4, placeholder: '', input_html: {class: "form-control"}
  .form-group.field_wrapper
    = label_tag 'terms', 'Set the Code of Conduct for your Group', class: "light"
    = f.text_area 'terms', label: false , class: 'form-control', rows: 4, placeholder: '', input_html: {class: "form-control"}

  - if locals[:group].new_record?
    .form-group.field_wrapper.group_rules
      = label_tag 'terms_of_gns', 'Read GroupnShop Terms of Use below', class: "light"
      iframe style="width: 100%; height: 300px" src="#{terms_of_use_path(no_layout: true)}"
      .checkbox
        = check_box_tag :check
        = label_tag 'check', 'By checking the box you are agreeing to the Terms of Use of Groupnshop', class: "light"
  .btn-area
    button.bz-oval-btn type="submit"
      =locals[:type]

app/views/groups/_group_items.slim
- if current_user.group_status(@group) == 'joined' || @group.user == current_user
  .row
    .col-xs-12
      h3.bz-subtitle
        | Invite your friends to join group!
      .invite-content
        = form_tag invite_to_group_path(group_id: @group.id)
          h4.light.label
            |Enter your friends’ email
          .form-group
            = text_field_tag 'email', nil, class: 'email', placeholder: '', required: true
            = submit_tag 'Send Invite', class: 'bz-oval-btn mc m-0'
          h4.subtitle.light
            |Enter multiple emails separated with commas.
      hr
.row
  .col-xs-12
    .bz-items-container
      - @group.items.active.each do |item|
        = render 'partials/new_bid', :locals => {item: item}

app/views/groups/_group_profile.slim
- if !@group.state.blank?
  - country_or_state = ' | ' + @group.state.upcase + ' '
-elsif !@group.country.blank?
  - country_or_state = ' | ' + @group.country.upcase + ' '
-else
  - country_or_state = ' | '

.col-xs-12.col-sm-7
  h3.bz-title
    = @group.title
  h3.bz-subtitle
    | Location
  p = @group.city + country_or_state  if @group.city
  h4.bz-subtitle
    | Description
  p.flex.-start aria-controls="desc" aria-expanded="true" data-target="#desc" data-toggle="collapse" type="button" 
    span
      - if @group.description.length > 565
        - desc_prev = @group.description[0,565] + "<span id='desc' class='bz-text-btn collapse in' aria-controls='expand_description' aria-expanded='false' data-target='#expand_description' data-toggle='collapse' type='button' > &nbsp;+more </span>"
        = desc_prev.html_safe
        span.collapse#expand_description
          - exp_desc = "&nbsp;" + @group.description[565,9999] + "<span class='bz-text-btn' aria-controls='expand_description' aria-expanded='false' data-target='#expand_description' data-toggle='collapse' type='button' > &nbsp;-less </span>"
          = exp_desc.html_safe
      - else
        = @group.description.html_safe
  h3.bz-subtitle
    | Code of Conduct 
  p = @group.terms

.col-xs-12.col-sm-5
  - if @group.file
    .flex.-end
      p.group_image.text-center
        =image_tag @group.file.thumb.url
  - if @group.user
    .flex.-end.column
      h4.bz-subtitle
        | Group Admin
      p = @group.user.first_name
      = link_to 'Send Message', new_account_message_path(recipient_id: @group.user.id)
  -if current_user
    .flex.-end
      - if can? :leave_group, @group
        -if current_user.group_status(@group) == "pending"
          .bz-oval-btn.disabled.bz-group-controls
            a class="bz-text-btn leave_group"
              span.regular Pending...
        -if current_user.group_status(@group) == "joined"
          .bz-oval-btn.disabled.bz-group-controls
            a class="bz-text-btn leave_group"
              |✓
              span.regular
                |Joined
        -if current_user.group_status(@group) == ""
          .bz-oval-btn.mc.bz-group-controls
            =render "groups/invite_buttons/join_group_btn", locals: {group: @group}
  -if can? :edit, @group
    .flex.-end
      = link_to 'Edit', edit_group_path(@group), class: 'bz-oval-btn fitted'

.col-xs-12
  hr
  .row
    - if current_user.group_status(@group) == 'joined' || @group.user == current_user
      .col-xs-12
        h3.bz-subtitle
          | Group Information
        .panel.panel-transparent role="tabpanel"
          ul.nav.nav-tabs.nav-justified
            li.active role="presentation"
              a.bb01 href="#members" aria-controls="members" role="tab" data-toggle="tab" aria-expanded="true"
                | Members
            li role="presentation"
              a.bb01 href="#pendings" aria-controls="pendings" role="tab" data-toggle="tab" aria-expanded="false"
                | Pending
          .tab-content.p0.bg-white
            #members.tab-pane.active
              table class="table table-bordered table-striped"
                thead
                  tr
                    th class="group_title" ID
                    th Name
                    tbody
                      - @group.group_memberships.not_pending.each do |gm|
                        tr
                          td =gm.user.id
                          td
                            .user-info
                              = link_to gm.user.first_name, group_user_path(@group, gm.user), class: "#{current_user == gm.user ? 'color-mc' : ''}"
                              p.controls
                                - if @group.user != gm.user
                                  - if @group.user == current_user && gm.status.to_s == 'joined'
                                    - if gm.role.to_s == 'user'
                                      = link_to appoint_group_admin_path({user_id: gm.user.id, group_id:  @group.id}), {method: :post, class: '', data:{:confirm => 'Are you sure you want to appoint '+ gm.user.full_name + ' as an additional Group Admin?'}} do
                                            button.bz-button 
                                              |Appoint as admin&nbsp;|&nbsp;
                                    - elsif gm.role.to_s == 'user'
                                      = link_to demote_group_admin_path({user_id: gm.user.id, group_id:  @group.id}), {method: :post, class: '', data:{:confirm => 'Are you sure you want to remove '+ gm.user.full_name + ' from additional Group Admin?'}} do
                                            button.bz-button 
                                              |Remove as Admin&nbsp;|&nbsp;

                                  -if @group.user == current_user || (@group.user_is_admin?(current_user) && gm.role.to_s != 'admin')
                                    - if gm.role.to_s != 'admin' || @group.group_admins.length > 1
                                      =render "groups/invite_buttons/remove_from_group_btn", locals: {group: @group, user: gm.user}
            #pendings.tab-pane
              table class="table table-bordered table-striped"
                thead
                  tr
                    th class="group_title" ID
                    th Name
                    tbody
                      - @group.group_memberships.pendings.each do |gm|
                        tr
                          td = gm.user.id
                          td
                            .user-info
                              = link_to gm.user.first_name, group_user_path(@group, gm.user), class: "#{current_user == gm.user ? 'color-mc' : ''}"
                              p.controls
                                -if (@group.user_is_admin?(current_user) || current_user == @group.user) && (gm.user != @group.user)
                                  =render "groups/invite_buttons/add_to_group_btn", locals: {group: @group, user: gm.user}

app/views/groups/add_to_group.js.erb
$('.add_to_group').on('ajax:send', function () {
}).on('ajax:complete', function () {
  $(this).parents('.controls').html("<%= j render 'groups/invite_buttons/remove_from_group_btn', locals: {group: @group, user: @user}%>");
}).on('ajax:error', function () {
}).on('ajax:success', function (data) {
});

app/views/groups/edit.slim
.bz-newgroup-page
  .container.newgroup-content
    h2.bz-title
      |Edit a Group
    h4.bz-subtitle
      |Edit this group as admin
    = render "group_form", locals: { group: @group, type: 'Update Group' }

app/views/groups/index.slim
.bz-groups-section
  .container
    h2.bz-title
      | Local Groups in
      span
        | &nbsp; #{@location}
    h4.bz-subtitle.bigger
      |Choose a Group or Groups to Join
    .bz-groups
      - @groups.each do |group|
        .col-xs-12.col-md-6
          = render 'group', group: group
      .col-xs-12.col-md-6
        = link_to new_group_path do
          .bz-group.new
            .bz-text-btn
              | + Create a Group
    .groups-action
      =link_to switch_groups_path
        h2.bz-title
          | Next Step
      =link_to root_path
        h4
          |Skip This Step ⤍
      h4.light
        |Just Post Your Items in Communities of Your Choice and Start Taking Bids

app/views/groups/invite_to_group.js.erb
$('.invite_to_group').on('ajax:send', function () {
}).on('ajax:complete', function () {
  console.log("<%= @msg %>", "DAAAAAAAAAAATA");
  $(".parsley-errors").html("<%= @msg %>")
  $('.submit-button').removeAttr('disabled')
}).on('ajax:error', function () {
}).on('ajax:success', function (data) {
});

app/views/groups/join_group.js.erb
window.location.reload(false)

app/views/groups/leave_group.js.erb
window.location.reload(false)

app/views/groups/new.slim
.bz-newgroup-page
  .container.newgroup-content
    h2.bz-title
      |Create a Group
    h4.bz-subtitle
      |Create Your Own Group and Invite Your Friends to Join
    = render "group_form", locals: { group: Group.new, type: 'Send for Approval' }

app/views/groups/remove_from_group.js.erb
$('.remove_from_group').on('ajax:send', function () {
}).on('ajax:complete', function () {
  $(this).parents('tr').remove();
}).on('ajax:error', function () {
}).on('ajax:success', function (data) {
});

app/views/groups/show.slim
.bz-group-page
  .container
    .panel.panel-default.group-form
      .panel-body
        .row
          .col-xs-12
            .group-banner
              =image_tag @group.banner
        .row
          .col-xs-12
            div role="tabpanel"
              ul.nav.nav-tabs.nav-justified
                li.active role="presentation"
                  a.bb01 href="#profile" aria-controls="profile" role="tab" data-toggle="tab" aria-expanded="true"
                    | Profile
                li role="presentation"
                  a.bb01 href="#items" aria-controls="items" role="tab" data-toggle="tab" aria-expanded="true"
                    | Items
              .tab-content.b0.bg-white
                #profile.tab-pane.active
                  = render 'group_profile'
                #items.tab-pane
                  = render 'group_items'

app/views/groups/switch.slim
.bz-groups-section
  .container
    h2.bz-title
      | List of My Groups
    h4.bz-subtitle
      | Select the Group You Want to Visit
    .bz-groups
      - @groups.each do |group|
        .col-xs-12.col-md-6
          = render 'switch_group', group: group
    .groups-action
      =link_to browse_select_path
        h2.bz-title
          | Continue Browsing