config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  
  root 'main#index'
# Content pages
  get 'how_it_works', to: 'main#how_it_works'
  get 'faqs', to: 'main#faqs'
  get 'prohibited_items', to: 'main#prohibited_items'
  get 'terms_of_use', to: 'main#terms_of_use'
  get 'privacy_policy', to: 'main#privacy_policy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
                      sessions: 'sessions',
                      registrations: 'registrations',
                      :confirmations => 'confirmations',
                      omniauth_callbacks: "users/omniauth_callbacks"
                     }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end


#BROSING
  get '/browse', to: 'browse#index', as: 'browse'
  get '/browse_select', to: 'browse#select', as: 'browse_select'
  get '/browse/categories', to: 'browse#category', as: 'browse_categories'

#Relationships
  resources :relationships, only: [:create, :destroy]

#Gropus
  resources :groups do
    post :block_user, on: :member
    post :unblock_user, on: :member

    resources :users, only: [:show] do
    end
  end

  get 'groups_search', to: 'groups#search', as: "groups_search"
  get 'switch_groups',                  to: 'groups#switch', as: :switch_groups
  post '/choose_group/:group_id',       to: 'groups#choose_group', as: 'choose_group'
  post '/switch_group/:group_id',       to: 'groups#switch_group', as: 'switch_group'
  post '/join_group/:group_id',         to: 'groups#join_group', as: 'join_group'
  post '/leave_group/:group_id',        to: 'groups#leave_group', as: 'leave_group'
  post '/add_to_group/:user_id',        to: 'groups#add_to_group', as: 'add_to_group'
  post '/invite_to_group',              to: 'groups#invite_to_group', as: 'invite_to_group' 
  delete '/remove_from_group/:user_id', to: 'groups#remove_from_group', as: 'remove_from_group'
  post '/appoint_group_admin/:user_id', to: 'groups#appoint_admin', as: 'appoint_group_admin'
  post '/demote_group_admin/:user_id',  to: 'groups#demote_user', as: 'demote_group_admin'
  get '/more_group_items', to: 'groups#load_more', as: 'more_group_items'

#Refferal
  post 'send_invite', to: 'referral#invite', as: :send_invite
  get 'invite', to: 'referral#index', as: :invite

#FAQ
  resources :faq_items
  get 'help', to: 'faq_items#index', as: :help

# DisputsComment
  resources :disput_comments

# Disputs
  resources :disputs
  get '/open_disput_modal', to: 'disputs#open_disput_modal', as: 'open_disput_modal'
  get '/resolve_disput_modal', to: 'disputs#resolve_disput_modal', as: 'resolve_disput_modal'

# Items
  resources :items
  get 'search', to: 'items#search', as: "search"
  post '/buy_now', to: 'items#buy_now', as: 'buy_now'
  post '/buy_free', to: 'items#buy_free', as: 'buy_free'
  post '/activate_payment/:id', to: 'items#activate_payment', as: 'activate_payment'
  post '/premium_payment/:id', to: 'items#premium_payment', as: 'premium_payment'
  post '/buy_item/:id', to: 'items#buy_item', as: 'buy_item'
  post '/item/:id/offer', to: 'items#make_an_offer', as: 'make_an_offer'
  get '/items/category/:category', to: "items#index", as: "items_category"
  post 'choose_winner/:id', to: 'items#choose_winner', as: 'choose_winner'
  post 'set_winner/:id', to: 'items#set_winner', as: 'set_winner'
  post 'finish/:id', to: 'items#finish_item', as: 'finish_item'
  post 'item/:id/publish', to: 'items#publish', as: 'publish_item'
  post 'item/save_to_draft', to: 'items#save_to_draft', as: 'save_to_draft'
  patch 'item/:id/save_to_draft', to: 'items#save_to_draft', as: 'update_to_draft'
  get '/choose_posting_type', to: "items#choose_type", as: "choose_posting_type"

# Charges
  resources :charges, only: [:new, :create]

  namespace :account do
    # Messages
    post '/messages/status/:id', to: 'messages#change_status', as: 'messages_change_status'
    get '/feedback_service', to: 'messages#feedback', as: 'feedback_service'
    resources :messages, :except => [:update] do
      collection do
        delete 'destroy_multiple', to: 'messages#destroy_multiple'
      end
    end
    resources :notifications, only: [:index, :destroy]
    get '/dashboard', to: 'dashboard#index'
    get '/profile', to: 'profile#edit'
    patch '/profile', to: 'profile#update'
    get '/items', to: 'dashboard#items'
    get '/feedbacks', to: 'dashboard#feedbacks'
    get '/bids', to: 'dashboard#bids'
  end

# Likes
  put '/likes/add_to_favorite/:id/:obj', to: 'likes#add_to_favorite', as: 'add_to_favorite'
  put '/likes/remove_from_favorite/:id/:obj', to: 'likes#remove_from_favorite', as: 'remove_from_favorite'

# Photos
  post '/images/:temp_key', to: 'images#create', as: 'images_create'
  resources :images, :only => [:index, :show, :destroy]

# Bids
  resources :bids, :only => [:create]
#Feedback
  resources :feedbacks, :only => [:new, :create]

#Users
  get 'settings', to: 'users#settings', as: 'settings'
  post 'notification_permit', to: 'users#set_notification_permit', as: 'set_notification_permit'
  get 'transactions', to: 'users#transactions', as: 'transactions'
  get 'security', to: 'users#security', as: 'security'
  post '/settings/set_currency/', to: 'users#set_currency', as: 'set_currency'
  get 'my_items', to: 'users#items', as: 'my_items'
  get 'dashboard', to: 'users#dashboard'
  get 'dashboard/feedbacks', to: 'users#feedbacks'
  get 'dashboard/bids', to: 'users#bids'
  resources :users do
    collection do
      get 'new_password'
      patch 'update_password'
    end
  end
  resources :password_resets

#Balance
  resources :withdraws, :only => [:new, :create]

# Pages
  get 'pages/:id', to: 'pages#show', as: 'pages'

  get '*path' =>  redirect('/')

end

app/views/layouts/partials/_flag.html.slim
- if current_user
  li.dropdown.dropdown-list
    a[href="#" data-toggle="dropdown"]
      span.flag-icon class="flag-icon-#{current_user.currency.short_country_name}"

    ul.dropdown-menu.animated.flipInX.currency-wrapper
      - Currency.all.each do |currency|
        li
          /a href="#" class="currency-#{currency.short_country_name}" data-id="#{currency.id}"
          = link_to set_currency_path(title: currency.id, format: :js), remote: true, method: :post
            span.flag-icon class="flag-icon-#{currency.short_country_name}"

app/views/layouts/partials/_footer.html.erb
<span>&copy; Groupnshop</span>

app/views/layouts/partials/_footer.html.slim
span
  | &copy; Groupnshop

app/views/layouts/partials/_google_analytics.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108108451-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-108108451-1');
</script>

app/views/layouts/partials/_gtag_iframe.html.erb
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MQBQVNV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

app/views/layouts/partials/_gtag_script.html.erb
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MQBQVNV');</script>
<!-- End Google Tag Manager -->

app/views/layouts/partials/_offsidebar.html.slim
nav
  div[role="tabpanel"]
    ul.nav.nav-tabs.nav-justified[role="tablist"]
      li.active[role="presentation"]
        a[href="#app-settings" aria-controls="app-settings" role="tab" data-toggle="tab"]
          em.icon-equalizer.fa-lg
      li[role="presentation"]
        a[href="#app-chat" aria-controls="app-chat" role="tab" data-toggle="tab"]
          em.icon-user.fa-lg
    .tab-content
      #app-settings.tab-pane.fade.in.active[role="tabpanel"]
        h3.text-center.text-thin
          | Settings
        .p
          h4.text-muted.text-thin
            | Layout
          .clearfix
            p.pull-left
              | Fixed
            .pull-right
              label.switch
                input#chk-fixed[type="checkbox" data-toggle-state="layout-fixed"]
                span
          .clearfix
            p.pull-left
              | Boxed
            .pull-right
              label.switch
                input#chk-boxed[type="checkbox" data-toggle-state="layout-boxed"]
                span
          .clearfix
            p.pull-left
              | RTL
            .pull-right
              label.switch
                input#chk-rtl[type="checkbox"]
                span
        .p
          h4.text-muted.text-thin
            | Aside
          .clearfix
            p.pull-left
              | Collapsed
            .pull-right
              label.switch
                input#chk-collapsed[type="checkbox" data-toggle-state="aside-collapsed"]
                span
          .clearfix
            p.pull-left
              | Collapsed Text
            .pull-right
              label.switch
                input#chk-collapsed-text[type="checkbox" data-toggle-state="aside-collapsed-text"]
                span
          .clearfix
            p.pull-left
              | Float
            .pull-right
              label.switch
                input#chk-float[type="checkbox" data-toggle-state="aside-float"]
                span
          .clearfix
            p.pull-left
              | Hover
            .pull-right
              label.switch
                input#chk-hover[type="checkbox" data-toggle-state="aside-hover"]
                span
          .clearfix
            p.pull-left
              | Show Scrollbar
            .pull-right
              label.switch
                input#chk-hover[type="checkbox" data-toggle-state="show-scrollbar" data-target=".sidebar"]
                span
      #app-chat.tab-pane.fade[role="tabpanel"]
        h3.text-center.text-thin
          | Connections
        ul.nav
          li.p
            small.text-muted
              | ONLINE
          li
            a.media-box.p.mt0[href="#"]
              span.pull-right
                span.circle.circle-success.circle-lg
              span.pull-left
                |  <img src="
                = image_path('angle/user/05.jpg')
                | " alt="Image" class="media-box-object img-circle thumb48" /> 
              span.media-box-body
                span.media-box-heading
                  strong
                    | Juan Sims
                  br
                  small.text-muted
                    | Designeer
            a.media-box.p.mt0[href="#"]
              span.pull-right
                span.circle.circle-success.circle-lg
              span.pull-left
                |  <img src="
                = image_path('angle/user/06.jpg')
                | " alt="Image" class="media-box-object img-circle thumb48" /> 
              span.media-box-body
                span.media-box-heading
                  strong
                    | Maureen Jenkins
                  br
                  small.text-muted
                    | Designeer
            a.media-box.p.mt0[href="#"]
              span.pull-right
                span.circle.circle-danger.circle-lg
              span.pull-left
                |  <img src="
                = image_path('angle/user/07.jpg')
                | " alt="Image" class="media-box-object img-circle thumb48" /> 
              span.media-box-body
                span.media-box-heading
                  strong
                    | Billie Dunn
                  br
                  small.text-muted
                    | Designeer
            a.media-box.p.mt0[href="#"]
              span.pull-right
                span.circle.circle-warning.circle-lg
              span.pull-left
                |  <img src="
                = image_path('angle/user/08.jpg')
                | " alt="Image" class="media-box-object img-circle thumb48" /> 
              span.media-box-body
                span.media-box-heading
                  strong
                    | Tomothy Roberts
                  br
                  small.text-muted
                    | Designer
          li.p
            small.text-muted
              | OFFLINE
          li
            a.media-box.p.mt0[href="#"]
              span.pull-right
                span.circle.circle-lg
              span.pull-left
                |  <img src="
                = image_path('angle/user/09.jpg')
                | " alt="Image" class="media-box-object img-circle thumb48" /> 
              span.media-box-body
                span.media-box-heading
                  strong
                    | Lawrence Robinson
                  br
                  small.text-muted
                    | Developer
            a.media-box.p.mt0[href="#"]
              span.pull-right
                span.circle.circle-lg
              span.pull-left
                |  <img src="
                = image_path('angle/user/10.jpg')
                | " alt="Image" class="media-box-object img-circle thumb48" /> 
              span.media-box-body
                span.media-box-heading
                  strong
                    | Tyrone Owens
                  br
                  small.text-muted
                    | Designer
          li
            .p-lg.text-center
              a.btn.btn-purple.btn-sm[href="#" title="See more contacts"]
                strong
                  | Load more..
        .p
          p
            small.text-muted
              | Tasks completion
          .progress.progress-xs.m0
            .progress-bar.progress-bar-success.progress-80[role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"]
              span.sr-only
                | 80% Complete
        .p
          p
            small.text-muted
              | Upload quota
          .progress.progress-xs.m0
            .progress-bar.progress-bar-warning.progress-40[role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"]
              span.sr-only
                | 40% Complete

app/views/layouts/partials/_sidebar.html.slim
.aside-inner
  nav.sidebar[data-sidebar-anyclick-close=""]
    ul.nav
      li.has-user-block
        #user-block.collapse
          .item.user-block
            .user-block-picture
              .user-block-status
                = image_tag current_user.avatar_url.blank? ? 'angle/dummy.png' : current_user.avatar_url , class: 'img-thumbnail img-circle', width: 60, width: 60
                .circle.circle-success.circle-lg
            .user-block-info
              span.user-block-name
                = "Hello, " + current_user.full_name
      li.nav-heading
        span
          | Main Navigation
      li class="#{'active' if controller?('account/dashboard') && action?('index')}"
        = link_to account_dashboard_path, title: 'Dashboard'
          em.icon-speedometer
          span[data-localize="sidebar.nav.DASHBOARD"] Dashboard
      li class="#{'active' if controller?('account/profile')}"
        = link_to account_profile_path, title: 'Profile' do
          em.icon-user
          span[data-localize="sidebar.nav.extra.MYPROFILE"] My Profile
      li class="#{'active' if controller?('account/messages')}"
        = link_to account_messages_path, title: 'Mailbox' do
          em.icon-envelope
          - if @inbox_msg_count>0
            .label.label-success.pull-right.inbox-count = @inbox_msg_count
          span[data-localize="sidebar.nav.extra.MAILBOX"] Mailbox
      li class="#{'active' if controller?('account/notifications')}"
        = link_to account_notifications_path, title: 'Dashboard'
          em.icon-bell
          span[data-localize="sidebar.nav.DASHBOARD"] Notifications
          - if current_user.notifications.news.count > 0
            .label.label-danger.pull-right
              = current_user.notifications.news.count
      li class="#{'active' if controller?('account/dashboard') && action?('items')}"
        = link_to account_items_path, title: 'My Posts' do
          em.icon-list
          span[data-localize="sidebar.nav.extra.MYITEMS"] My Posts
      li class="#{'active' if controller?('account/dashboard') && action?('feedbacks')}"
        = link_to account_feedbacks_path, title: 'My Reviews' do
          em.icon-bubble
          /.label.label-success.pull-right 
          span[data-localize="sidebar.nav.extra.MYREVIEWS"] My Reviews
      li
        = link_to browse_path(favorites: true), title: 'My Favorites' do
          em.icon-star
          /.label.label-success.pull-right 
          span[data-localize="sidebar.nav.extra.MAILBOX"] My Favorites
      li class="#{'active' if controller?('account/dashboard') && action?('bids')}"
        = link_to account_bids_path, title: 'My Bids' do
          em.icon-calendar
          /.label.label-success.pull-right 
          span[data-localize="sidebar.nav.extra.MYREVIEWS"] Bids & Offers

app/views/layouts/partials/_topnavbar.html.slim
nav.navbar.topnavbar.second[role="navigation"]
  .navbar-header
    button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
      span.sr-only
        | Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand[href="/"]
      .brand-logo
        = image_tag 'logo.png', alt: 'App Logo', class: 'img-responsive'
      .brand-logo-collapsed
        = image_tag 'favicon.png', alt: 'App Logo', class: 'img-responsive'
  .nav-wrapper
    ul.nav.navbar-nav
      li
        a.hidden-xs[href="#" data-trigger-resize="" data-toggle-state="aside-collapsed"]
          em.fa.fa-navicon
        a.visible-xs.sidebar-toggle[href="#" data-toggle-state="aside-toggled" data-no-persist="true"]
          em.fa.fa-navicon
      li
        a#user-block-toggle.hidden-xs[href="#user-block" data-toggle="collapse"]
          em.icon-user
    ul.nav.navbar-nav.navbar-collapse.collapse
      li
        = active_link_to "Browse", browse_path
      li
        = active_link_to "Join a Group", groups_path, active: [['groups'], ['index']]
      li
        = active_link_to "Invite friends", invite_path
      li
        = link_to 'Post', choose_posting_type_path, :method => :get
      li
        = active_link_to "My groups", switch_groups_path, active: [['groups'], ['switch']]

    ul.nav.navbar-nav.navbar-right.navbar-collapse.collapse
      li
        = link_to how_it_works_path
          |How To
          i class="fa fa-lightbulb-o"

      - if @inbox_msg_count
        li.dropdown.dropdown-list
          a[href="#" data-toggle="dropdown"]
            em.icon-envelope
            - if @inbox_msg_count > 0
              .label.label-warning
                = @inbox_msg_count
          ul.dropdown-menu.animated.flipInX
            li
              .list-group
                = link_to browse_path(following: true), class: "list-group-item"
                  .media-box
                    .pull-left
                      em.fa.fa-shopping-cart.fa-2x.text-info
                    .media-box-body.clearfix
                      p.m0
                        | Following Items
                      p.m0.text-muted
                        small
                          | You are following #{pluralize(current_user.followed_items.active.count, 'item')} 
                a.list-group-item[href="#"]
                  .media-box
                    .pull-left
                      em.fa.fa-envelope.fa-2x.text-warning
                    .media-box-body.clearfix
                      p.m0
                        | Mail
                      p.m0.text-muted
                        small
                          | You have #{@inbox_msg_count} new emails

        li
          = link_to account_notifications_path
            em.icon-bell
            - if current_user.notifications.news.count > 0
              .label.label-danger
                = current_user.notifications.news.count

      li.dropdown.dropdown-list
        a[href="#" data-toggle="dropdown"]
          - if current_user.avatar_url.present?
            = image_tag current_user.avatar_url
          - else
            em.icon-user
          = current_user.first_name + ' ' + current_user.last_name
        ul.dropdown-menu.animated.flipInX
          li
            .list-group
              = link_to account_dashboard_path, class: "list-group-item"
                .media-box
                  .pull-left
                    / em.fa.fa-settings.fa-2x
                  .media-box-body.clearfix
                    p.m0 My Account
              = link_to settings_path, class: "list-group-item"
                .media-box
                  .pull-left
                    / em.fa.fa-settings.fa-2x
                  .media-box-body.clearfix
                    p.m0 Settings
              = link_to transactions_path, class: "list-group-item"
                .media-box
                  .pull-left
                  .media-box-body.clearfix
                    p.m0 Transactions
              = link_to account_feedback_service_path, class: "list-group-item"
                .media-box
                  .pull-left
                  .media-box-body.clearfix
                    p.m0 Feedback
              = link_to security_path, class: "list-group-item"
                .media-box
                  .pull-left
                  .media-box-body.clearfix
                    p.m0 Security
              = link_to destroy_user_session_path, method: :delete, class: "list-group-item"
                .media-box
                  .pull-left
                  .media-box-body.clearfix
                    p.m0 Logout
      = render 'layouts/partials/flag'
      li
        a[href="#" data-search-open=""]
          em.icon-magnifier
      li.visible-lg
        a[href="#" data-toggle-fullscreen=""]
          em.fa.fa-expand

  = search_form_for @q, url: browse_path, html: {class: 'navbar-form', role: 'search'} do |f|
    .form-group.has-feedback
      = f.search_field :title_cont, class: 'form-control', placeholder: 'I’m looking for…'
      .fa.fa-times.form-control-feedback[data-search-dismiss=""]

app/views/layouts/partials/_topnavbar_h.html.slim
nav.navbar.topnavbar[role="navigation"]
  .navbar-wrapper
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand[href="/"]
        .brand-logo
          = image_tag 'logo.png', alt: 'App Logo', class: 'img-responsive'
        .brand-logo-collapsed
          = image_tag 'favicon.png', alt: 'App Logo', class: 'img-responsive'
    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li
          = active_link_to "Browse", browse_path
        li
          = active_link_to "Join a Group", groups_path, active: [['groups'], ['index']]
        li
          = active_link_to "Invite friends", invite_path
        li
          = link_to 'Post', choose_posting_type_path, :method => :get
        li
          = active_link_to "My groups", switch_groups_path, active: [['groups'], ['switch']]

      ul.nav.navbar-nav.navbar-right
        li
          = link_to how_it_works_path
            |How To 
            i class="fa fa-lightbulb-o"

        - if @inbox_msg_count
          li.dropdown.dropdown-list
            a[href="#" data-toggle="dropdown"]
              em.icon-envelope
              - if @inbox_msg_count > 0
                .label.label-warning
                  = @inbox_msg_count
            ul.dropdown-menu.animated.flipInX
              li
                .list-group
                  = link_to browse_path(following: true), class: "list-group-item"
                    .media-box
                      .pull-left
                        em.fa.fa-shopping-cart.fa-2x.text-info
                      .media-box-body.clearfix
                        p.m0
                          | Following Items
                        p.m0.text-muted
                          small
                            | You are following #{pluralize(current_user.followed_items.active.count, 'item')} 
                  a.list-group-item[href="#{account_messages_path}"]
                    .media-box
                      .pull-left
                        em.fa.fa-envelope.fa-2x.text-warning
                      .media-box-body.clearfix
                        p.m0
                          | Mail
                        p.m0.text-muted
                          small
                            | You have #{@inbox_msg_count} new emails
        
          li
            = link_to account_notifications_path
              em.icon-bell
              - if current_user.notifications.news.count > 0
                .label.label-danger
                  = current_user.notifications.news.count

        - if current_user
          li.dropdown.dropdown-list
            a[href="#" data-toggle="dropdown"]
              - if current_user.avatar_url.present?
                = image_tag current_user.avatar_url
              - else
                em.icon-user
              = current_user.first_name + ' ' + current_user.last_name
            ul.dropdown-menu.animated.flipInX
              li
                .list-group
                  = link_to account_dashboard_path, class: "list-group-item"
                    .media-box
                      .pull-left
                        / em.fa.fa-settings.fa-2x
                      .media-box-body.clearfix
                        p.m0 My Account
                  = link_to settings_path, class: "list-group-item"
                    .media-box
                      .pull-left
                        / em.fa.fa-settings.fa-2x
                      .media-box-body.clearfix
                        p.m0 Settings
                  = link_to transactions_path, class: "list-group-item"
                    .media-box
                      .pull-left
                      .media-box-body.clearfix
                        p.m0 Transactions
                  = link_to account_feedback_service_path, class: "list-group-item"
                    .media-box
                      .pull-left
                      .media-box-body.clearfix
                        p.m0 Feedback
                  = link_to security_path, class: "list-group-item"
                    .media-box
                      .pull-left
                      .media-box-body.clearfix
                        p.m0 Security
                  = link_to destroy_user_session_path, method: :delete, class: "list-group-item"
                    .media-box
                      .pull-left
                      .media-box-body.clearfix
                        p.m0 Logout
        - else
          li
            = link_to root_path(anchor: "sign_section")
              | Login
        = render 'layouts/partials/flag'
        li
          a[href="#" data-search-open=""]
            em.icon-magnifier
        li.visible-lg
          a[href="#" data-toggle-fullscreen=""]
            em.fa.fa-expand
  = search_form_for @q, url: browse_path, html: {class: 'navbar-form', role: 'search'} do |f|
    .form-group.has-feedback
      = f.search_field :title_cont, class: 'form-control', placeholder: 'I’m looking for…'
      .fa.fa-times.form-control-feedback[data-search-dismiss=""]