config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  
  root 'main#index'
# Content pages
  get 'how_it_works', to: 'main#how_it_works'
  get 'faqs', to: 'main#faqs'
  get 'prohibited_items', to: 'main#prohibited_items'
  get 'terms_of_use', to: 'main#terms_of_use'
  get 'privacy_policy', to: 'main#privacy_policy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
                      sessions: 'sessions',
                      registrations: 'registrations',
                      :confirmations => 'confirmations',
                      omniauth_callbacks: "users/omniauth_callbacks"
                     }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end


#BROSING
  get '/browse', to: 'browse#index', as: 'browse'
  get '/browse_select', to: 'browse#select', as: 'browse_select'
  get '/browse/categories', to: 'browse#category', as: 'browse_categories'

#Relationships
  resources :relationships, only: [:create, :destroy]

#Gropus
  resources :groups do
    post :block_user, on: :member
    post :unblock_user, on: :member

    resources :users, only: [:show] do
    end
  end

  get 'groups_search', to: 'groups#search', as: "groups_search"
  get 'switch_groups',                  to: 'groups#switch', as: :switch_groups
  post '/choose_group/:group_id',       to: 'groups#choose_group', as: 'choose_group'
  post '/switch_group/:group_id',       to: 'groups#switch_group', as: 'switch_group'
  post '/join_group/:group_id',         to: 'groups#join_group', as: 'join_group'
  post '/leave_group/:group_id',        to: 'groups#leave_group', as: 'leave_group'
  post '/add_to_group/:user_id',        to: 'groups#add_to_group', as: 'add_to_group'
  post '/invite_to_group',              to: 'groups#invite_to_group', as: 'invite_to_group' 
  delete '/remove_from_group/:user_id', to: 'groups#remove_from_group', as: 'remove_from_group'
  post '/appoint_group_admin/:user_id', to: 'groups#appoint_admin', as: 'appoint_group_admin'
  post '/demote_group_admin/:user_id',  to: 'groups#demote_user', as: 'demote_group_admin'
  get '/more_group_items', to: 'groups#load_more', as: 'more_group_items'

#Refferal
  post 'send_invite', to: 'referral#invite', as: :send_invite
  get 'invite', to: 'referral#index', as: :invite

#FAQ
  resources :faq_items
  get 'help', to: 'faq_items#index', as: :help

# DisputsComment
  resources :disput_comments

# Disputs
  resources :disputs
  get '/open_disput_modal', to: 'disputs#open_disput_modal', as: 'open_disput_modal'
  get '/resolve_disput_modal', to: 'disputs#resolve_disput_modal', as: 'resolve_disput_modal'

# Items
  resources :items
  get 'search', to: 'items#search', as: "search"
  post '/buy_now', to: 'items#buy_now', as: 'buy_now'
  post '/buy_free', to: 'items#buy_free', as: 'buy_free'
  post '/activate_payment/:id', to: 'items#activate_payment', as: 'activate_payment'
  post '/premium_payment/:id', to: 'items#premium_payment', as: 'premium_payment'
  post '/buy_item/:id', to: 'items#buy_item', as: 'buy_item'
  post '/item/:id/offer', to: 'items#make_an_offer', as: 'make_an_offer'
  get '/items/category/:category', to: "items#index", as: "items_category"
  post 'choose_winner/:id', to: 'items#choose_winner', as: 'choose_winner'
  post 'set_winner/:id', to: 'items#set_winner', as: 'set_winner'
  post 'finish/:id', to: 'items#finish_item', as: 'finish_item'
  post 'item/:id/publish', to: 'items#publish', as: 'publish_item'
  post 'item/save_to_draft', to: 'items#save_to_draft', as: 'save_to_draft'
  patch 'item/:id/save_to_draft', to: 'items#save_to_draft', as: 'update_to_draft'
  get '/choose_posting_type', to: "items#choose_type", as: "choose_posting_type"

# Charges
  resources :charges, only: [:new, :create]

  namespace :account do
    # Messages
    post '/messages/status/:id', to: 'messages#change_status', as: 'messages_change_status'
    get '/feedback_service', to: 'messages#feedback', as: 'feedback_service'
    resources :messages, :except => [:update] do
      collection do
        delete 'destroy_multiple', to: 'messages#destroy_multiple'
      end
    end
    resources :notifications, only: [:index, :destroy]
    get '/dashboard', to: 'dashboard#index'
    get '/profile', to: 'profile#edit'
    patch '/profile', to: 'profile#update'
    get '/items', to: 'dashboard#items'
    get '/feedbacks', to: 'dashboard#feedbacks'
    get '/bids', to: 'dashboard#bids'
  end

# Likes
  put '/likes/add_to_favorite/:id/:obj', to: 'likes#add_to_favorite', as: 'add_to_favorite'
  put '/likes/remove_from_favorite/:id/:obj', to: 'likes#remove_from_favorite', as: 'remove_from_favorite'

# Photos
  post '/images/:temp_key', to: 'images#create', as: 'images_create'
  resources :images, :only => [:index, :show, :destroy]

# Bids
  resources :bids, :only => [:create]
#Feedback
  resources :feedbacks, :only => [:new, :create]

#Users
  get 'settings', to: 'users#settings', as: 'settings'
  post 'notification_permit', to: 'users#set_notification_permit', as: 'set_notification_permit'
  get 'transactions', to: 'users#transactions', as: 'transactions'
  get 'security', to: 'users#security', as: 'security'
  post '/settings/set_currency/', to: 'users#set_currency', as: 'set_currency'
  get 'my_items', to: 'users#items', as: 'my_items'
  get 'dashboard', to: 'users#dashboard'
  get 'dashboard/feedbacks', to: 'users#feedbacks'
  get 'dashboard/bids', to: 'users#bids'
  resources :users do
    collection do
      get 'new_password'
      patch 'update_password'
    end
  end
  resources :password_resets

#Balance
  resources :withdraws, :only => [:new, :create]

# Pages
  get 'pages/:id', to: 'pages#show', as: 'pages'

  get '*path' =>  redirect('/')

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  rescue_from Stripe::CardError, with: :catch_exception

  def new
    @item = Item.find_by(id: params[:item_id])
    @charge_amount = params[:charge_amount]
  end

  def create
    StripeChargesServices.new(charges_params, current_user, @item, @charge_amount).call
    redirect_to new_charge_path
  end

  private

  def charges_params
    params.permit(:stripeEmail, :stripeToken)
  end

  def catch_exception(exception)
    flash[:error] = exception.message
  end

end

app/views/charges/_checkout_address.html.erb
<p class="dl-address">Delivery Address</p>

<div class="row">
  <div class="col-md-6">
    <div class="form-group required">
      <label for="first_name" class="control-label">First Name</label>
      <input type="text" class="form-control" name="first_name" id="first_name">
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group required">
      <label for="last_name" class="control-label">Last Name</label>
      <input type="text" class="form-control" name="last_name" id="last_name">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="form-group required">
      <label for="email" class="control-label">Email Address</label>
      <input type="email" class="form-control" name="email" id="email">
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group required">
      <label for="phone" class="control-label">Phone</label>
      <input type="text" class="form-control" name="phone" id="phone">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group required">
      <label for="country" class="control-label">Country</label>
      <div class="form-control select">
        <select name="country" id="country" class="form-control">
          <option value="1">
            England
          </option>
          <option value="2">
            United States
          </option>
          <option value="3">
            Canada
          </option>
        </select>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group required">
      <label for="st_address" class="control-label">Address</label>
      <input type="text" class="form-control" name="st_address" id="st_address" placeholder="Street address">
      <input type="text" class="form-control" name="ap_address" id="ap_address" placeholder="Apartment, suite, unit etc. (optional)">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group required">
      <label for="city" class="control-label">Town / City</label>
      <input type="text" class="form-control" name="city" id="city">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="form-group required">
      <label for="state" class="control-label">State / Country</label>
      <input type="text" class="form-control" name="state" id="state">
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group required">
      <label for="zip" class="control-label">Postcode / Zip</label>
      <input type="text" class="form-control" name="zip" id="zip">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group d-flex justify-center">
      <button type="button" class="bz-oval-btn mc" id="nextToAddress">NEXT</button>
    </div>
  </div>
</div>

app/views/charges/_checkout_confirmation.html.erb
<p class="dl-address">Payment Confirmation</p>

<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table custom-datatable">
        <thead>
        <tr>
          <th><h4 class="pc-data">PRODUCT</h4></th>
          <th><h4 class="pc-data">RENT PER DAY</h4></th>
          <th><h4 class="pc-data">TOTAL RENT</h4></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>Item Description</td>
          <td>$250.00</td>
          <td>$1500.00</td>
        </tr>
        <tr>
          <td class="border-none">Drop-off Service</td>
          <td class="border-none"></td>
          <td class="border-none">$20.00</td>
        </tr>
        <tr>
          <td colspan="2"><h4 class="pc-data">TOTAL</h4></td>
          <td><h4 class="pc-data">$1520.00</h4></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 d-flex justify-center" style="margin-top: 30px;">
    <h4>Would you like to confirm your order for payment?</h4>
  </div>
  <div class="col-md-6">
    <div class="form-group d-flex justify-center">
      <button type="button" class="bz-oval-btn mc prev" id="beforeToConfirmation">Previous</button>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group d-flex justify-center">
      <button type="submit" class="bz-oval-btn mc" id="nextToConfirmation">Yes, Proceed Payment</button>
    </div>
  </div>
</div>

app/views/charges/_checkout_method.html.erb
<p class="dl-address">Choose Your Payment Method</p>

<div class="row">
  <div class="col-md-12">
    <div class="form-group required">
      <label for="cc_number" class="control-label">Credit Card Number</label>
      <input type="text" class="form-control" name="cc_number" id="cc_number">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="form-group required">
      <label for="cvv_code" class="control-label">CVV Code</label>
      <input type="text" class="form-control" name="cvv_code" id="cvv_code">
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group required">
      <label for="expired_date" class="control-label">Expiry Date</label>
      <input type="text" class="form-control" name="expired_date" id="expired_date">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="form-group required">
      <label for="card_name" class="control-label">Name on Card</label>
      <input type="text" class="form-control" name="card_name" id="card_name">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="form-group d-flex justify-center">
      <button type="button" class="bz-oval-btn mc prev" id="beforeToMethod">Previous</button>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group d-flex justify-center">
      <button type="button" class="bz-oval-btn mc" id="nextToMethod">Complete Payment</button>
    </div>
  </div>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @charge.amount %></strong>!</h2>

app/views/charges/new.html.erb
<%= content_for :stripe do %>
    <%= javascript_include_tag "https://js.stripe.com/v1/", "https://checkout.stripe.com/checkout.js" %>
    <%= tag :meta, :name => "stripe-key", :content => Rails.configuration.stripe[:publishable_key] %>
<% end %>
<%= content_for :js do %>
    <%= javascript_include_tag 'charges' %>
<% end %>

<div class="bz-newgroup-page item-checkout">
  <div class="container d-flex justify-center">
    <div class="col-md-10">
      <h2 class="bz-title">
        Checkout Process
      </h2>
      <div class="bz-tabs-section">
        <%= form_tag charges_path do %>
            <div class="nav" role="tablist" style="display: none;">
              <a href="#sub-pane-1" id="tab-1" data-toggle="tab"></a>
              <a href="#sub-pane-2" id="tab-2" data-toggle="tab"></a>
              <a href="#sub-pane-3" id="tab-3" data-toggle="tab"></a>
            </div>

            <div class="tab-content container">
              <div role="tabpanel" class="tab-pane active" id="sub-pane-1">
                <%= render 'checkout_address' %>
              </div>
              <div role="tabpanel" class="tab-pane" id="sub-pane-2">
                <%= render 'checkout_method' %>
              </div>
              <div role="tabpanel" class="tab-pane" id="sub-pane-3">
                <%= render 'checkout_confirmation' %>
              </div>
            </div>
        <% end %>
        </div>
  </div>
</div>
</div>